---
- hosts: dev
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Installing nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
  
    - name: Uploading webpage
      synchronize:
        src: ../root/
        dest: /var/www/html
        mode: push
        recursive: yes
